# Generated by Django 4.2.11 on 2024-03-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
