# Generated by Django 4.2.11 on 2024-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='field_2',
            field=models.CharField(default='hello_world!'),
        ),
        migrations.AddField(
            model_name='comment',
            name='field_3',
            field=models.CharField(null=True),
        ),
    ]
