# Generated by Django 4.2.11 on 2024-03-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_alter_comment_field_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='field_2',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='field_3',
        ),
    ]
